// Copyright 2026 randomtiwary
// SPDX-License-Identifier: Apache-2.0
//
// LEARNER: This header is the bridge from "bytes on disk" to protobuf's
// onnx::ModelProto. PR3a only *parses*; PR3b maps fields into our Graph IR.
//
// Spec: ONNX IR.md — Model; onnx.proto — message ModelProto

#pragma once

#include <cstdint>
#include <memory>
#include <string>

#include "eduort/status.h"

// Generated by protoc from third_party/onnx/onnx.proto (build tree).
#include "onnx.pb.h"

namespace eduort {

// Default max size for a model file read (design: 64 MiB parse cap).
constexpr std::size_t kDefaultMaxModelBytes = 64ull << 20;

// Read a .onnx file into an onnx::ModelProto.
//
// Failures:
//   kInvalidArgument — empty path, oversize file
//   kModelLoad       — I/O error or protobuf parse failure
//
// On success the ModelProto has been ParseFromArray'd. Callers should check
// model->has_graph() for a usable graph (smoke test does).
StatusOr<std::unique_ptr<onnx::ModelProto>> LoadModelProtoFromFile(
    const std::string& path,
    std::size_t max_bytes = kDefaultMaxModelBytes);

// Same as above but from an in-memory buffer (useful for tests).
StatusOr<std::unique_ptr<onnx::ModelProto>> LoadModelProtoFromBytes(
    const void* data,
    std::size_t size);

}  // namespace eduort
